import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import { Raleway } from 'next/font/google'
 
const raleway = Raleway({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-raleway'
})
 
export const metadata: Metadata = {
  title: 'Form Fit AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${raleway.className}`} lang="en">
      <body >{children}</body>
    </html>
  )
}
